name = "lanterna"
compatibility_date = "2026-07-01"
pages_build_output_dir = "dist"

[vars]
APP_URL = "https://deliver.lanterna.studio"
PUBLIC_DELIVERY_BASE_URL = "https://deliver.lanterna.studio"
EMAIL_PROVIDER = "resend"
